version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Installs Greenkeeper lockfile dependency globally
          command: sudo yarn global add greenkeeper-lockfile@2
      - restore_cache:
          name: Restores the Yarn package cache if possible
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install package dependencies
          command: yarn install
      - save_cache:
          name: Saves the Yarn package cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Updates the lockfile through Greenkeeper
          command: greenkeeper-lockfile-update
      - run:
          name: Run unit tests with code
          command: yarn test:cov
      - store_artifacts:
          path: coverage
      - run:
          name: Upload test coverage report to Codecov
          command: yarn codecov
      - run:
          name: Build the Typescript files
          command: yarn build
      - run:
          name: Uploads the lockfile through Greenkeeper
          command: greenkeeper-lockfile-upload
