version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - '88:6f:95:4d:b2:1a:5e:25:cc:d5:7f:ac:25:93:2e:11'
      - run:
          name: Setup git author email address
          command: git config user.email "$USER_EMAIL"
      - run:
          name: Setup git author name
          command: git config user.name "$USER_NAME"
      - checkout
      - run:
          name: Installs Greenkeeper lockfile dependency globally
          command: sudo yarn global add greenkeeper-lockfile@2
      - restore_cache:
          name: Restores the Yarn package cache if possible
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install package dependencies
          command: yarn install
      - save_cache:
          name: Saves the Yarn package cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Updates the lockfile through Greenkeeper
          command: greenkeeper-lockfile-update
      - run:
          name: Run unit tests with code
          command: yarn test:cov
      - store_artifacts:
          path: coverage
      - run:
          name: Upload test coverage report to Codecov
          command: yarn codecov
      - run:
          name: Build the Typescript files
          command: yarn build
      - run:
          name: Uploads the lockfile through Greenkeeper
          command: greenkeeper-lockfile-upload
